version: '2'

labels:

    rocks.puffin.name: Redmine 
    rocks.puffin.subtitle: project management and issue tracking tool
    rocks.puffin.website: http://www.redmine.org/ 
    rocks.puffin.description: |
        Redmine is a web-based project management and issue tracking tool.
        Default username: admin, password: admin

services:

    main:
        image: loomchild/redmine
        ports: 
            - 3000
        volumes: 
            - main_data:/usr/src/redmine/files
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
        networks:
            - front
            - back
            - default

volumes:
    main_data:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
