version: '2'

services:

    main:
        image: puffinrocks/redmine:latest
        ports: 
            - 3000
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST
            - LETSENCRYPT_EMAIL
            - LETSENCRYPT_TEST
        networks:
            - front
            - back
            - default
        volumes:
            - main_data:/usr/src/redmine/files
        tmpfs:
            - /run
            - /tmp

volumes:
    main_data:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
